### ISSUE TITLE
No registered env with id: UnrealArm-ContinuousPose-v1

### ISSUE THREAD

**Issue by shengweigit** [zfw1226/craves_control#3]
When I running main.py script I get "No registered env with id: UnrealArm-ContinuousPose-v1"  with argument " errors. Where I can get the environment of "UnrealArm-ContinuousPose-v1". Thanks.

`/home/sw/py3_virtualenv/bin/python3.5 /home/sw/project/craves/craves_control-master/ddpg/main.py --gpu-ids 0 --rescale --test --env UnrealArm-ContinuousPose-v1 --model-dir models/best.pt
using gpu 0
Traceback (most recent call last):
  File "/home/sw/py3_virtualenv/lib/python3.5/site-packages/gym/envs/registration.py", line 143, in spec
    return self.env_specs[id]
KeyError: 'UnrealArm-ContinuousPose-v1'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sw/project/craves/craves_control-master/ddpg/main.py", line 57, in <module>
    test(device, args)
  File "/home/sw/project/craves/craves_control-master/ddpg/test.py", line 10, in test
    env = create_env(args.env, args)
  File "/home/sw/project/craves/craves_control-master/ddpg/environment.py", line 17, in create_env
    env = gym.make(env_id)
  File "/home/sw/py3_virtualenv/lib/python3.5/site-packages/gym/envs/registration.py", line 167, in make
    return registry.make(id)
  File "/home/sw/py3_virtualenv/lib/python3.5/site-packages/gym/envs/registration.py", line 118, in make
    spec = self.spec(id)
  File "/home/sw/py3_virtualenv/lib/python3.5/site-packages/gym/envs/registration.py", line 153, in spec
    raise error.UnregisteredEnv('No registered env with id: {}'.format(id))
gym.error.UnregisteredEnv: No registered env with id: UnrealArm-ContinuousPose-v1`

**Comment by zfw1226** [comment]
Hi, I am sorry for the late update.
Currently, the `UnrealArm-ContinuousPose-v1` is only registered in the `develop` branch.  So you have to clone this branch to run the robotarm environment.

Note that please remember to run ``python load_env.py -e Arm`` to load the env binary at the beginning.
