### ISSUE TITLE
NotImplementedError: Operation not supported or unimplemented on this platform

### ISSUE THREAD

**Issue by zyx792726304** [zfw1226/craves_control#5]
The following code occures when running :
                  python demo_control.py --kp --pose 0 0 0 0

D:\craves_control-master\craves_control>python demo_control.py --kp --pose 0 0 0 0
D:\craves_control-master\craves_control\utils\trans.py:1926: UserWarning: No module named 'craves_control.utils._transformations'
  warnings.warn(str(err))
usb cam started!
Traceback (most recent call last):
  File "demo_control.py", line 34, in <module>
    arm_ctl = usb_arm.Arm()  # inti arm controller
  File "D:\craves_control-master\craves_control\hardware\usb_arm.py", line 68, in __init__
    self.dev.set_configuration()
  File "F:\anaconda\envs\pytorch_zyx\lib\site-packages\usb\core.py", line 869, in set_configuration
    self._ctx.managed_set_configuration(self, configuration)
  File "F:\anaconda\envs\pytorch_zyx\lib\site-packages\usb\core.py", line 102, in wrapper
    return f(self, *args, **kwargs)
  File "F:\anaconda\envs\pytorch_zyx\lib\site-packages\usb\core.py", line 147, in managed_set_configuration
    self.managed_open()
  File "F:\anaconda\envs\pytorch_zyx\lib\site-packages\usb\core.py", line 102, in wrapper
    return f(self, *args, **kwargs)
  File "F:\anaconda\envs\pytorch_zyx\lib\site-packages\usb\core.py", line 120, in managed_open
    self.handle = self.backend.open_device(self.dev)
  File "F:\anaconda\envs\pytorch_zyx\lib\site-packages\usb\backend\libusb1.py", line 786, in open_device
    return _DeviceHandle(dev)
  File "F:\anaconda\envs\pytorch_zyx\lib\site-packages\usb\backend\libusb1.py", line 643, in __init__
    _check(_lib.libusb_open(self.devid, byref(self.handle)))
  File "F:\anaconda\envs\pytorch_zyx\lib\site-packages\usb\backend\libusb1.py", line 593, in _check
    raise NotImplementedError(_strerror(ret))
NotImplementedError: Operation not supported or unimplemented on this platform

**Comment by zfw1226** [comment]
Hi, the issue seems caused by the USB driver problem on Windows.
This implementation is built on Linux (ubuntu 14.04/16.04).
So you'd better run on Linux instead of Windows.

**Comment by zyx792726304** [comment]
I have the following questions:
1.Does the four parameters of pose_deg mean the degree of rotation,base,elbow,wrist?Why the pose_deg changes when we just move the whole robot arm without changing the position of camera and the motors?
2.Why 'bad pose' occurs frequently?When I implement 'demo_control.py --kp --pose 0 0 0 0 ',the arm moves and stuck in 'bad pose'.and it stops.So how can I trumph over it?Is it for my bad position of my camera?How should I place it?

Thank you!

**Comment by zfw1226** [comment]
Hi, the following is my answer to your questions:
1.  The four parameters correspond to the estimated angle of the motors in degree. the pose_deg may have slightly changed because the position the 2D keypoints is impacted by the quality of the image.
2. The `bad pose` warning appears when the estimated is not continuous to previously estimated pose or out of the safe range. So you'd better reset the pose and camera position manually once your arm is stopped with the `bad pose` warning.
